(defun even-positions (lst)
  (if (null lst)
      lst
      (let ((count 0)
            result)
        (flet ((push-if-even (x)
                 (if (evenp count)
                     (progn
                       (push x result)
                       (setf count (1+ count)))
                     (setf count (1+ count)))))
        (mapcar #'push-if-even
                    
                lst)
          (reverse result)))))

(defun odd-positions (lst)
  (if (null lst)
      lst
      (let ((count 0)
            result)
        (flet ((push-if-odd (x)
                 (if (oddp count)
                     (progn
                       (push x result)
                       (setf count (1+ count)))
                     (setf count (1+ count)))))
        (mapcar #'push-if-odd
                    
                lst)
          (reverse result)))))


(odd-positions '(1 1 3 4 5))

(defun fft (a)
  "The length of array a must be a power of 2"
  (flet ((euler (n)
           (complex (cos (/ (* pi 2) n))
                    (sin (/ (* pi 2) n)))))
    (let ((len (length a)))
      (when (= 1 len)
        (return-from fft a))
      (let* ((omega-n (euler len))
             (omega 1)
             (subarray-even (even-positions a))
             (subarray-odd (odd-positions a))
             (y_0 (fft subarray-even))
             (y_1 (fft subarray-odd)))
        (let ((result (loop for i from 0 to len collect 0)))
          (loop for i from 0 to (- (/ len 2) 1)
                do (setf (nth i result)
                         (+ (nth i y_0)
                            (* omega (nth i y_1))))
                   (setf (nth (+ i (/ len 2)) result)
                         (- (nth i y_0)
                            (* omega (nth i y_1))))
                   (setf omega (* omega omega-n)))
          result)))))

(mapcar #'abs (fft (loop for i from 1 to 4096 collect (random 1.0))))
(fft '(1 1  0 1 -1 1 0 1 1 1  0 1 -1 1 0 1 1 1  0 1 -1 1 0 1 1 1  0 1 -1 1 0 1))
(fft '(1 1 1 1))
(fft '(1 .5 1 .5))

(defun inverse-fft (a)
  "The length of array a must be a power of 2"
  (flet ((euler (n)
           (complex (cos (/ (* pi 2) n))
                    (- (sin (/ (* pi 2) n))))))
    (let ((len (length a)))
      (when (= 1 len)
        (return-from fft a))
      (let* ((omega-n (euler len))
             (omega 1)
             (subarray-even (even-positions a))
             (subarray-odd (odd-positions a))
             (y_0 (inverse-fft subarray-even))
             (y_1 (inverse-fft subarray-odd)))
        (let ((result (loop for i from 0 to len collect 0)))
          (loop for i from 0 to (- (/ len 2) 1)
                do (setf (nth i result)
                         (+ (nth i y_0)
                            (* omega (nth i y_1))))
                   (setf (nth (+ i (/ len 2)) result)
                         (- (nth i y_0)
                            (* omega (nth i y_1))))
                   (setf omega (* omega omega-n)))
          result)))))
