;;; Inverse FFT
(defun %inverse-fft (a &optional len)
  "The length of array a must be a power of 2"
  (flet ((euler (n)
           (complex (cos (/ (* pi 2) n))
                    (- (sin (/ (* pi 2) n))))))
    (let ((len (or len (length a))))
      (when (= 1 len)
        (return-from %inverse-fft a))
      (let* ((omega-n (euler len))
             (omega 1)
             (subarray-even (even-positions a))
             (subarray-odd (odd-positions a))
             (y_0 (%inverse-fft subarray-even))
             (y_1 (%inverse-fft subarray-odd)))
        (let ((result (loop for i from 0 to (1- len) collect 0)))
          (loop for i from 0 to (- (/ len 2) 1)
                do (setf (nth i result)
                         (+ (nth i y_0)
                            (* omega (nth i y_1))))
                   (setf (nth (+ i (/ len 2)) result)
                         (- (nth i y_0)
                            (* omega (nth i y_1))))
                   (setf omega (* omega omega-n)))
          result)))))

(defun inverse-fft (a)
  (let ((len (length a)))
    (mapcar #'(lambda (x) (/ x len)) (%inverse-fft a len))))
